# The number of trials of a fuzzer-benchmark pair to do.
trials: 5

# The amount of time in seconds that each trial is run for.
# 1 day = 24 * 60 * 60 = 86400
max_total_time: 30

# The name of your Google Cloud project.
cloud_project: hadai-research

# The Google Compute Engine zone to run the experiment in.
cloud_compute_zone: us-west1-b

# The Google Cloud Storage bucket that will store most of the experiment data.
cloud_experiment_bucket: gs://fuzzbench_data

# The bucket where HTML reports and summary data will be stored.
cloud_web_bucket: gs://fuzzbench_results

# The connection to use to connect to the Google Cloud SQL instance.
cloud_sql_instance_connection_name: "hadai-research:us-west1:fuzztest=tcp:5432"
